In [1]:
import numpy as np
import pandas as pd 

In [2]:
df=pd.read_csv("blackFriday_train.csv")

In [3]:
df.head(10)

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000001  P00069042      F   0-17          10             A   
1  1000001  P00248942      F   0-17          10             A   
2  1000001  P00087842      F   0-17          10             A   
3  1000001  P00085442      F   0-17          10             A   
4  1000002  P00285442      M    55+          16             C   
5  1000003  P00193542      M  26-35          15             A   
6  1000004  P00184942      M  46-50           7             B   
7  1000004  P00346142      M  46-50           7             B   
8  1000004   P0097242      M  46-50           7             B   
9  1000005  P00274942      M  26-35          20             A   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   
5                          3               0                   1   
6                          2               1                   1   
7                          2               1                   1   
8                          2               1                   1   
9                          1               1                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969  
5                 2.0                 NaN     15227  
6                 8.0                17.0     19215  
7                15.0                 NaN     15854  
8                16.0                 NaN     15686  
9                 NaN                 NaN      7871

In [4]:
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [6]:
df["User_ID"].unique()

array([1000001, 1000002, 1000003, ..., 1004113, 1005391, 1001529],
      dtype=int64)

In [7]:
df["Product_ID"].unique()

array(['P00069042', 'P00248942', 'P00087842', ..., 'P00370293',
       'P00371644', 'P00370853'], dtype=object)

In [8]:
df["Gender"].unique()

array(['F', 'M'], dtype=object)

In [9]:
df["Age"].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [10]:
df["Occupation"].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6], dtype=int64)

In [11]:
df["City_Category"].unique()

array(['A', 'C', 'B'], dtype=object)

In [12]:
df["Stay_In_Current_City_Years"].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [13]:
df["Marital_Status"].unique()

array([0, 1], dtype=int64)

In [14]:
df["Product_Category_1"].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19], dtype=int64)

In [15]:
df["Product_Category_2"].unique()

array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [16]:
df["Product_Category_3"].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [17]:
df=df.drop("Product_ID",axis=1)

In [18]:
df.head()

User_ID Gender   Age  Occupation City_Category Stay_In_Current_City_Years  \
0  1000001      F  0-17          10             A                          2   
1  1000001      F  0-17          10             A                          2   
2  1000001      F  0-17          10             A                          2   
3  1000001      F  0-17          10             A                          2   
4  1000002      M   55+          16             C                         4+   

   Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3  \
0               0                   3                 NaN                 NaN   
1               0                   1                 6.0                14.0   
2               0                  12                 NaN                 NaN   
3               0                  12                14.0                 NaN   
4               0                   8                 NaN                 NaN   

   Purchase  
0      8370  
1     15200  
2      1422  
3      1057  
4      7969

In [19]:
(df["Gender"])=df["Gender"].map({'F':0,'M':1})
(df['Age'])=df["Age"].map({'0-17':1,'18-25':2,'26-35':3,'36-45':4,'46-50':5,'51-55':6,'55+':7})
(df['City_Category'])=df['City_Category'].map({'A':1, 'C':2, 'B':3})
df['Stay_In_Current_City_Years']=df['Stay_In_Current_City_Years'].str.replace('+','')
df['Stay_In_Current_City_Years']=df['Stay_In_Current_City_Years'].astype(int)

C:\Users\Prashant Pathak\AppData\Local\Temp\ipykernel_3872\1501523432.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Stay_In_Current_City_Years']=df['Stay_In_Current_City_Years'].str.replace('+','')


In [20]:
df.head()

User_ID  Gender  Age  Occupation  City_Category  \
0  1000001       0    1          10              1   
1  1000001       0    1          10              1   
2  1000001       0    1          10              1   
3  1000001       0    1          10              1   
4  1000002       1    7          16              2   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                           2               0                   3   
1                           2               0                   1   
2                           2               0                  12   
3                           2               0                  12   
4                           4               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [21]:
(df['Product_Category_2'])=df['Product_Category_2'].fillna(df['Product_Category_2'].mode()[0])
(df['Product_Category_3'])=df['Product_Category_3'].fillna(df['Product_Category_3'].mode()[0])

In [22]:
df.head()

User_ID  Gender  Age  Occupation  City_Category  \
0  1000001       0    1          10              1   
1  1000001       0    1          10              1   
2  1000001       0    1          10              1   
3  1000001       0    1          10              1   
4  1000002       1    7          16              2   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                           2               0                   3   
1                           2               0                   1   
2                           2               0                  12   
3                           2               0                  12   
4                           4               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 8.0                16.0      8370  
1                 6.0                14.0     15200  
2                 8.0                16.0      1422  
3                14.0                16.0      1057  
4                 8.0                16.0      7969

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Gender                      550068 non-null  int64  
 2   Age                         550068 non-null  int64  
 3   Occupation                  550068 non-null  int64  
 4   City_Category               550068 non-null  int64  
 5   Stay_In_Current_City_Years  550068 non-null  int32  
 6   Marital_Status              550068 non-null  int64  
 7   Product_Category_1          550068 non-null  int64  
 8   Product_Category_2          550068 non-null  float64
 9   Product_Category_3          550068 non-null  float64
 10  Purchase                    550068 non-null  int64  
dtypes: float64(2), int32(1), int64(8)
memory usage: 44.1 MB


In [24]:
df.describe()

User_ID         Gender            Age     Occupation  \
count  5.500680e+05  550068.000000  550068.000000  550068.000000   
mean   1.003029e+06       0.753105       3.496430       8.076707   
std    1.727592e+03       0.431205       1.353632       6.522660   
min    1.000001e+06       0.000000       1.000000       0.000000   
25%    1.001516e+06       1.000000       3.000000       2.000000   
50%    1.003077e+06       1.000000       3.000000       7.000000   
75%    1.004478e+06       1.000000       4.000000      14.000000   
max    1.006040e+06       1.000000       7.000000      20.000000   

       City_Category  Stay_In_Current_City_Years  Marital_Status  \
count  550068.000000               550068.000000   550068.000000   
mean        2.151714                    1.858418        0.409653   
std         0.815963                    1.289443        0.491770   
min         1.000000                    0.000000        0.000000   
25%         1.000000                    1.000000        0.000000   
50%         2.000000                    2.000000        0.000000   
75%         3.000000                    3.000000        1.000000   
max         3.000000                    4.000000        1.000000   

       Product_Category_1  Product_Category_2  Product_Category_3  \
count       550068.000000       550068.000000       550068.000000   
mean             5.404270            9.260768           14.989567   
std              3.936211            4.294093            2.739846   
min              1.000000            2.000000            3.000000   
25%              1.000000            8.000000           16.000000   
50%              5.000000            8.000000           16.000000   
75%              8.000000           14.000000           16.000000   
max             20.000000           18.000000           18.000000   

            Purchase  
count  550068.000000  
mean     9263.968713  
std      5023.065394  
min        12.000000  
25%      5823.000000  
50%      8047.000000  
75%     12054.000000  
max     23961.000000

# Model prepration:

In [27]:
x=df.drop(columns='Purchase')
y=df["Purchase"]

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [29]:
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
r2_score(y_test,y_pred)

0.13076466027027356

In [30]:
import xgboost

In [31]:
xgr=xgboost.XGBRegressor()
xgr.fit(x_train,y_train)
y_pred=xgr.predict(x_test)
r2_score(y_test,y_pred)

0.6834257666561445

In [32]:
from sklearn.ensemble import RandomForestRegressor

In [36]:
import pickle
saved_model = pickle.dumps(xgr)

In [38]:
xgr_from_pickle = pickle.loads(saved_model)

# prediction for test dataset.

In [40]:
test_df=pd.read_csv("blackFriday_test.csv")

In [43]:
test_df.head()

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000004  P00128942      M  46-50           7             B   
1  1000009  P00113442      M  26-35          17             C   
2  1000010  P00288442      F  36-45           1             B   
3  1000010  P00145342      F  36-45           1             B   
4  1000011  P00053842      F  26-35           1             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               1                   1   
1                          0               0                   3   
2                         4+               1                   5   
3                         4+               1                   4   
4                          1               0                   4   

   Product_Category_2  Product_Category_3  
0                11.0                 NaN  
1                 5.0                 NaN  
2                14.0                 NaN  
3                 9.0                 NaN  
4                 5.0                12.0

In [44]:
test_df=test_df.drop("Product_ID",axis=1)

In [46]:
(test_df["Gender"])=test_df["Gender"].map({'F':0,'M':1})
(test_df['Age'])=test_df["Age"].map({'0-17':1,'18-25':2,'26-35':3,'36-45':4,'46-50':5,'51-55':6,'55+':7})
(test_df['City_Category'])=test_df['City_Category'].map({'A':1, 'C':2, 'B':3})
test_df['Stay_In_Current_City_Years']=test_df['Stay_In_Current_City_Years'].str.replace('+','')
test_df['Stay_In_Current_City_Years']=test_df['Stay_In_Current_City_Years'].astype(int)

C:\Users\Prashant Pathak\AppData\Local\Temp\ipykernel_3872\1932039887.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  test_df['Stay_In_Current_City_Years']=test_df['Stay_In_Current_City_Years'].str.replace('+','')


In [47]:
(test_df['Product_Category_2'])=test_df['Product_Category_2'].fillna(test_df['Product_Category_2'].mode()[0])
(df['Product_Category_3'])=test_df['Product_Category_3'].fillna(test_df['Product_Category_3'].mode()[0])

In [48]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     233599 non-null  int64  
 1   Gender                      233599 non-null  int64  
 2   Age                         233599 non-null  int64  
 3   Occupation                  233599 non-null  int64  
 4   City_Category               233599 non-null  int64  
 5   Stay_In_Current_City_Years  233599 non-null  int32  
 6   Marital_Status              233599 non-null  int64  
 7   Product_Category_1          233599 non-null  int64  
 8   Product_Category_2          233599 non-null  float64
 9   Product_Category_3          71037 non-null   float64
dtypes: float64(2), int32(1), int64(7)
memory usage: 16.9 MB


In [51]:
new_pred=xgr_from_pickle.predict(test_df)

In [52]:
print(new_pred)

[14377.707  10226.325   5967.504  ... 12247.034  19276.873   3449.6667]
